name: Playwright Tests
on:
  push:
    branches: [ continuous ]
  pull_request:
    branches: [ main ]
env:
  AZCOPY_AUTO_LOGIN_TYPE: SPN
  AZCOPY_SPA_APPLICATION_ID: '${{ secrets.AZCOPY_SPA_APPLICATION_ID }}'
  AZCOPY_SPA_CLIENT_SECRET: '${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}'
  AZCOPY_TENANT_ID: '${{ secrets.AZCOPY_TENANT_ID }}'
  AD_STORAGE_NAME: '${{ vars.AD_STORAGE_NAME }}'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    - name: Run playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Upload HTML report to Azure
      shell: bash
      run: |
        REPORT_DIR='run-${{ github.run_id }}-${{ github.run_attempt }}'
        azcopy cp --recursive "./playwright-report/*" "https://${{ vars.AD_STORAGE_NAME }}.blob.core.windows.net/\$web/$REPORT_DIR"
        echo "::notice title=HTML report url::https://${{ vars.AD_STORAGE_NAME }}.z13.web.core.windows.net/$REPORT_DIR/index.html"
